"""initial migration

Revision ID: 7915216062dd
Revises: 
Create Date: 2025-06-04 22:39:32.721144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7915216062dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='clase_ejemplo'
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='clase_ejemplo'
    )
    op.create_table('libro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('publicacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='clase_ejemplo'
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    schema='clase_ejemplo'
    )
    op.create_table('libro_autor',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['clase_ejemplo.autor.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['clase_ejemplo.libro.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'autor_id'),
    schema='clase_ejemplo'
    )
    op.create_table('libro_categoria',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['clase_ejemplo.categoria.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['clase_ejemplo.libro.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'categoria_id'),
    schema='clase_ejemplo'
    )
    op.create_table('prestamo',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('prestamo', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('devolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['clase_ejemplo.libro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['clase_ejemplo.usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'libro_id'),
    schema='clase_ejemplo'
    )
    op.create_table('multa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('pagado', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('prestamo_usuario_id', sa.Integer(), nullable=True),
    sa.Column('prestamo_libro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prestamo_usuario_id', 'prestamo_libro_id'], ['clase_ejemplo.prestamo.usuario_id', 'clase_ejemplo.prestamo.libro_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clase_ejemplo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multa', schema='clase_ejemplo')
    op.drop_table('prestamo', schema='clase_ejemplo')
    op.drop_table('libro_categoria', schema='clase_ejemplo')
    op.drop_table('libro_autor', schema='clase_ejemplo')
    op.drop_table('usuario', schema='clase_ejemplo')
    op.drop_table('libro', schema='clase_ejemplo')
    op.drop_table('categoria', schema='clase_ejemplo')
    op.drop_table('autor', schema='clase_ejemplo')
    # ### end Alembic commands ###
